/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filaatendimento;

import javax.swing.JOptionPane;

/**
 *
 * @author mauri
 */
public class TelaTriagem1 extends NFrame {

    /**
     * Creates new form TelaTriagem1
     */
    public TelaTriagem1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloTriagem = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        ChamaC = new javax.swing.JButton();
        ChamaP = new javax.swing.JButton();
        ChamaP1 = new javax.swing.JButton();
        ChamaC1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloTriagem.setFont(new java.awt.Font("Palatino Linotype", 1, 20)); // NOI18N
        TituloTriagem.setText("  Triagem");
        TituloTriagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Sair.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        ChamaC.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        ChamaC.setText("Chamar Comum");
        ChamaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaCActionPerformed(evt);
            }
        });

        ChamaP.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        ChamaP.setText("Chamar Preferencial");
        ChamaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaPActionPerformed(evt);
            }
        });

        ChamaP1.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        ChamaP1.setText("Chamar Preferencial Emergência");
        ChamaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaP1ActionPerformed(evt);
            }
        });

        ChamaC1.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        ChamaC1.setText("Chamar Comum Emergência");
        ChamaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TituloTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Sair))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChamaP1)
                                    .addComponent(ChamaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChamaP, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(ChamaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TituloTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChamaP1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChamaP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChamaC1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChamaC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(Sair)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Voltando para a tela principal");
        TelaHome2 th= new TelaHome2();
        th.setLocationRelativeTo(null);
        th.setVisible(true);
        this.dispose();
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ChamaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaCActionPerformed
        // TODO add your handling code here:
        if(Scomum.lerPrimeiraSenhaDoArquivo() != null){
        JOptionPane.showMessageDialog(null, "Primeiro da fila foi chamado: " + Scomum.lerPrimeiraSenhaDoArquivo()); 
        Scomum.removerPrimeiraSenha();
        }
        else{
            JOptionPane.showMessageDialog(null, "Não há próximo da fila.");
        }
   
        
        
    }//GEN-LAST:event_ChamaCActionPerformed
        
    private void ChamaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaPActionPerformed
        // TODO add your handling code here:
        if(Sprefe.lerPrimeiraSenhaDoArquivo() != null){
        JOptionPane.showMessageDialog(null, "Primeiro da fila foi chamado: " + Sprefe.lerPrimeiraSenhaDoArquivo()); 
        Sprefe.removerPrimeiraSenha();
        }
        else{
            JOptionPane.showMessageDialog(null, "Não há próximo da fila.");
        }
        
        
    }//GEN-LAST:event_ChamaPActionPerformed

    private void ChamaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaP1ActionPerformed
        // TODO add your handling code here:
       if(SprefeEm.lerPrimeiraSenhaDoArquivo() != null){
        JOptionPane.showMessageDialog(null, "Primeiro da fila foi chamado: " + SprefeEm.lerPrimeiraSenhaDoArquivo()); 
        SprefeEm.removerPrimeiraSenha();
        }
        else{
            JOptionPane.showMessageDialog(null, "Não há próximo da fila.");
        }
        
    }//GEN-LAST:event_ChamaP1ActionPerformed

    private void ChamaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaC1ActionPerformed
        // TODO add your handling code here:
        if(ScomumEm.lerPrimeiraSenhaDoArquivo() != null){
        JOptionPane.showMessageDialog(null, "Primeiro da fila foi chamado: " + ScomumEm.lerPrimeiraSenhaDoArquivo()); 
        ScomumEm.removerPrimeiraSenha();
        }
        else{
            JOptionPane.showMessageDialog(null, "Não há próximo da fila.");
        }
        
    }//GEN-LAST:event_ChamaC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriagem1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChamaC;
    private javax.swing.JButton ChamaC1;
    private javax.swing.JButton ChamaP;
    private javax.swing.JButton ChamaP1;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel TituloTriagem;
    // End of variables declaration//GEN-END:variables
}
